# NOTE: exclude
#  Single file/folder -> exclude: examples/.*ipynb
#  Multiple file/folder -> exclude: (^.*<folder_name>/|examples/.*ipynb)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      #  - id: check-symlinks
      #  - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: fix-encoding-pragma
        args: ["--remove"]
        description: Removes the encoding-pragma since python3 codes are utf-8 by default
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      # Run the Ruff linter.
      - id: ruff
      # Run the Ruff formatter.
      - id: ruff-format

  # NOTE: It doesn't use pyproject.toml configs. We might enable it the future.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       files: bert_score_api
  #       additional_dependencies: [types-PyYAML, rich]
  #       args: [
  #           "--strict",
  #           # "--config-file=pyproject.toml",
  #           # "--ignore-missing-imports",
  #         ]
