site_name: Bert Score Api
site_dir: public
site_url: https://github.com/ilkersigirci/bert-score-api
# repo_url: https://gitlab.com/ilkersigirci/bert-score-api # # For GitLab
repo_url: https://ilkersigirci.github.io/bert-score-api/ # For GitHub
# repo_name: GitLab
repo_name: GitHub

theme:
  name: material
  palette:
    primary: blue
    accent: blue

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            # Headings options
            show_root_heading: false
            # Members options
            show_submodules: true
            # Docstrings options
            docstring_style: google
            # docstring_options
            docstring_section_style: table
            line_length: 88
            merge_init_into_class: true
            # Signatures/annotations options
            show_signature: true
            show_signature_annotations: false
            separate_signature: true
            # Additional options
            show_bases: true
            show_source: true

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
